[package]
name = "rask-resolve"
version.workspace = true
edition.workspace = true

[dependencies]
rask-ast = { path = "../rask-ast" }
rask-lexer = { path = "../rask-lexer" }
rask-parser = { path = "../rask-parser" }
thiserror.workspace = true

[dev-dependencies]
tempfile = "3"
