# SPDX-License-Identifier: (MIT OR Apache-2.0)
[package]
name = "rask-lexer"
version.workspace = true
edition.workspace = true

[dependencies]
rask-ast = { path = "../rask-ast" }
thiserror.workspace = true
logos.workspace = true
