[package]
name = "rask-types"
version.workspace = true
edition.workspace = true

[dependencies]
rask-ast = { path = "../rask-ast" }
rask-resolve = { path = "../rask-resolve" }
rask-stdlib = { path = "../rask-stdlib" }
thiserror.workspace = true
